-------------------------------------------------------------------------------
Test set: pro.abacus.javatutor.SecurityIntegrationTest
-------------------------------------------------------------------------------
Tests run: 6, Failures: 2, Errors: 1, Skipped: 0, Time elapsed: 166.75 s <<< FAILURE! - in pro.abacus.javatutor.SecurityIntegrationTest
loginUserAccessProtected(pro.abacus.javatutor.SecurityIntegrationTest)  Time elapsed: 17.548 s  <<< FAILURE!
java.lang.AssertionError: Authentication should not be null
	at pro.abacus.javatutor.SecurityIntegrationTest.loginUserAccessProtected(SecurityIntegrationTest.java:66)

loginWithMockUser(pro.abacus.javatutor.SecurityIntegrationTest)  Time elapsed: 30.549 s  <<< ERROR!
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.dao.DataAccessResourceFailureException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]
	at pro.abacus.javatutor.SecurityIntegrationTest.loginWithMockUser(SecurityIntegrationTest.java:59)
Caused by: org.springframework.dao.DataAccessResourceFailureException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]
	at pro.abacus.javatutor.SecurityIntegrationTest.loginWithMockUser(SecurityIntegrationTest.java:59)
Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]
	at pro.abacus.javatutor.SecurityIntegrationTest.loginWithMockUser(SecurityIntegrationTest.java:59)

loginUser(pro.abacus.javatutor.SecurityIntegrationTest)  Time elapsed: 30.018 s  <<< FAILURE!
java.lang.AssertionError: Authentication should not be null
	at pro.abacus.javatutor.SecurityIntegrationTest.loginUser(SecurityIntegrationTest.java:45)

